config/routes.rb
Gpt::Application.routes.draw do
  resources :devices

  resources :gps_points do
      collection do
        get :manual
        post :manual
      end

  end

  

end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :gps_points
  validates :name, :presence => true
end

app/models/gps_point.rb
class GpsPoint < ActiveRecord::Base

  belongs_to :device
  validates :latitude, :numericality => { :greater_than_or_equal_to => -90, :less_than_or_equal_to => 90 }, :presence => true
  validates :longitude, :numericality => { :greater_than_or_equal_to => -180, :less_than_or_equal_to => 180 }, :presence => true
  validates :device_id, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name)
    end
end

app/controllers/gps_points_controller.rb
class GpsPointsController < ApplicationController
  before_action :set_gps_point, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:manual]
  # GET /gps_points
  # GET /gps_points.json
  def index
    @gps_points = GpsPoint.order('created_at desc').limit(100)
    #@gps_points = GpsPoint.find(:all, :order => "attending DESC")
  end

  # GET /gps_points/1
  # GET /gps_points/1.json
  def show
  end

  # GET /gps_points/new
  def new
    @gps_point = GpsPoint.new
  end

  # GET /gps_points/1/edit
  def edit
  end

  # POST /gps_points
  # POST /gps_points.json
  def create
    @gps_point = GpsPoint.new(gps_point_params)

    respond_to do |format|
      if @gps_point.save
        format.html { redirect_to @gps_point, notice: 'Gps point was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gps_point }
      else
        format.html { render action: 'new' }
        format.json { render json: @gps_point.errors, status: :unprocessable_entity }
      end
    end
  end


  def manual
    latitude=params[:latitude]
    longitude=params[:longitude]
    accuracy = params[:accuracy]
    provider = params[:provider]
    timestamp= params[:timestamp]

    imei=params[:imei]

    pointnew = GpsPoint.new
    pointnew.latitude=latitude
    pointnew.longitude=longitude
    pointnew.accuracy=accuracy
    pointnew.provider=provider


    id_device=0
    b = Device.find_by_name(params[:imei])
    if b.present?
      id_device = b.id
    else
      a=Device.new
      a.name=params[:imei]
      if a.valid?
        a.save
      else
        render :json => 'KO'
        return false
      end
      a.save
      id_device = a.id

    end

    pointnew.device_id = id_device


    if pointnew.valid?
      pointnew.save
     render :json =>  pointnew
    else
      render :json => 'KO'
    end

  end
  # PATCH/PUT /gps_points/1
  # PATCH/PUT /gps_points/1.json
  def update
    respond_to do |format|
      if @gps_point.update(gps_point_params)
        format.html { redirect_to @gps_point, notice: 'Gps point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gps_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gps_points/1
  # DELETE /gps_points/1.json
  def destroy
    @gps_point.destroy
    respond_to do |format|
      format.html { redirect_to gps_points_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gps_point
      @gps_point = GpsPoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gps_point_params
      params.require(:gps_point).permit(:latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/gps_points_helper.rb
module GpsPointsHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <%
           @puntos = GpsPoint.where('device_id=?',device.id).order("created_at desc").limit(20)
           @PuntosCada = @puntos.map { |i| [i[:latitude], i[:longitude]] }

              a=Polylines::Encoder.encode_points(@PuntosCada)

        %>
        <td> <img src="http://maps.googleapis.com/maps/api/staticmap?sensor=true&size=1000x1000&markers=color:blue%7Clabel:S%7C<%= @puntos.first.latitude.to_s %>,<%= @puntos.first.longitude.to_s%>&path=weight:3%7Ccolor:0x0000ff%7Cenc:<%=a%>"> </td>



      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>



<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/gps_points/_form.html.erb
<%= form_for(@gps_point) do |f| %>
  <% if @gps_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gps_point.errors.count, "error") %> prohibited this gps_point from being saved:</h2>

      <ul>
      <% @gps_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gps_points/edit.html.erb
<h1>Editing gps_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @gps_point %> |
<%= link_to 'Back', gps_points_path %>

app/views/gps_points/index.html.erb
<h1>Listing gps_points</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Accuracy</th>
      <th>Provider</th>
      <th>IMEI</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gps_points.each do |gps_point| %>
      <tr>
        <td><%= gps_point.latitude %></td>
        <td><%= gps_point.longitude %></td>
        <td><%= gps_point.accuracy %></td>
        <td><%= gps_point.provider %></td>
        <td><%= Device.find(gps_point.device_id).name %></td>
        <td><%= time_ago_in_words(gps_point.created_at) + " ago"%></td>
        <td><%= link_to 'Show', gps_point %></td>
        <td><%= link_to 'Edit', edit_gps_point_path(gps_point) %></td>
        <td><%= link_to 'Destroy', gps_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gps point', new_gps_point_path %>

app/views/gps_points/new.html.erb
<h1>New gps_point</h1>

<%= render 'form' %>

<%= link_to 'Back', gps_points_path %>

app/views/gps_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @gps_point.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @gps_point.longitude %>
</p>

<%= link_to 'Edit', edit_gps_point_path(@gps_point) %> |
<%= link_to 'Back', gps_points_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gpt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>